######################################################################
# Automatically generated by qmake (3.0) Wed Dec 13 10:30:13 2017
######################################################################

CONFIG += console
QT += network
TEMPLATE = app
TARGET = server
INCLUDEPATH += .

# Input
SOURCES += main.cpp
