######################################################################
# Automatically generated by qmake (3.0) Wed Dec 13 15:40:13 2017
######################################################################

QT -= gui
QT += network
TARGET = server
CONFIG += console
CONFIG -= app_bundle
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += server.h
SOURCES += main.cpp server.cpp
